---
 - hosts: all
   become: yes
   remote_user: ubuntu
   tasks:
   - name: Get public IP
     community.general.ipify_facts:

   - name: Delete previous deploy directory
     file: 
       path: '{{ deploy_directory }}'
       state: absent
       
   - name: Create Directory
     file: 
       path: /home/bootcamp/
       state: directory
       mode: '0755'

   - name: Sync between the control machine and remote host
     ansible.posix.synchronize:
       src:  /home/agent/agent/_work/r2/a/bootcamp-app
       dest: /home/bootcamp/
       
   - name: Sleep 5 seconds and continue
     wait_for:
       timeout: 5  

   - name: Create environment variables file
     copy:
       dest: /home/bootcamp/bootcamp-app/.env
       content: |
         PORT={{ http_port }}
         HOST='0.0.0.0'
         HOST_URL=http://{{ ipify_public_ip }}:{{ http_port }}
         COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
         NODE_ENV=development
         PGHOST={{ pg_host }}
         PGUSERNAME={{ pg_username }}
         PGDATABASE={{ pg_database }}
         PGPASSWORD={{ pg_password }}
         PGPORT=5432
         OKTA_ORG_URL={{ okta_org_url }}
         OKTA_CLIENT_ID={{ okta_client_id }}
         OKTA_CLIENT_SECRET={{ okta_client_secret }}

   - name: Database initialization
     shell: npm run initdb
     async: 30
     poll: 0
     args:
       chdir: '{{ deploy_directory }}/'

   - name: Install nodemon
     npm:
       name: nodemon
       state: present
       global: yes    

   - name: Install pm2
     shell: npm install pm2 -g

   - name: Clear pm2 process
     shell: pm2 delete all
     ignore_errors: yes

   - name: Run application
     shell: pm2 start npm -- run dev && pm2 save && pm2 startup
     args:
       chdir: bootcamp-app/

   - name: Reboot
     reboot: